# Generated by Django 5.2.5 on 2025-09-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
